on: [push]

jobs:
  environme_job:
    runs-on: ubuntu-latest
    name: Environ Me
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Environ Me action step
        id: EnvironMe
        uses: urbanantics/environme-github-action@v1
        with:
          path: '*'
      - run: pwd
      - run: ls .
      - run: ls -lart /home/runner/work/environme-github-action/environme-github-action
      - run: ls -lart /home/runner/work/environme-github-action/
      - run: ls -lart /home/runner/work/
      - run: ls -lart /home/runner/
      - run: ls -lart /home/